/-
Copyright (c) 2025 PhysLean Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: PhysLean Contributors
-/

import PhysLean.Mathematics.Geometry.Metric.PseudoRiemannian.Einstein
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Linearized Gravity and Gravitational Waves

This file develops the theory of linearized gravity and gravitational waves,
describing weak gravitational fields as small perturbations of flat spacetime.

## Main Definitions

* `MetricPerturbation`: The metric as η_μν + h_μν where h is a small perturbation
* `GaugeTransformation`: Infinitesimal coordinate transformations
* `TTGauge`: The transverse-traceless gauge for gravitational waves
* `GravitationalWave`: A propagating solution to the linearized Einstein equations
* `GWPolarization`: The plus (+) and cross (×) polarization modes

## Physical Background

Gravitational waves are:
- Ripples in spacetime curvature propagating at the speed of light
- Transverse and traceless (2 independent polarizations)
- Generated by accelerating masses (quadrupole formula)
- Detected by measuring tidal forces (geodesic deviation)

The linearized theory is valid when |h_μν| << 1, i.e., weak gravitational fields.

## References

* Misner, Thorne, Wheeler, "Gravitation" (1973), Chapters 35-36
* Maggiore, "Gravitational Waves" (2007)
* Wald, "General Relativity" (1984), Chapter 4
-/

noncomputable section

namespace PseudoRiemannianMetric

/-! ## Linearized Metric Perturbation -/

/-- A metric perturbation h_μν representing a weak gravitational field.
The full metric is g_μν = η_μν + h_μν where |h| << 1.

In 4D, h_μν has 10 independent components (symmetric 4×4 matrix).
Gauge freedom removes 4 components, leaving 6.
In vacuum, tracelessness and transversality leave 2 (polarizations). -/
structure MetricPerturbation where
  /-- The perturbation tensor h_μν as a symmetric bilinear form.
      Indices run from 0 to 3 for (t, x, y, z). -/
  h : Fin 4 → Fin 4 → ℝ → ℝ → ℝ → ℝ → ℝ  -- h_μν(t, x, y, z)
  /-- Symmetry: h_μν = h_νμ -/
  symm : ∀ μ ν t x y z, h μ ν t x y z = h ν μ t x y z

/-- The trace of the metric perturbation: h = η^μν h_μν.
With signature (-,+,+,+): h = -h_00 + h_11 + h_22 + h_33 -/
def MetricPerturbation.trace (hp : MetricPerturbation) (t x y z : ℝ) : ℝ :=
  -hp.h 0 0 t x y z + hp.h 1 1 t x y z + hp.h 2 2 t x y z + hp.h 3 3 t x y z

/-- The Minkowski metric component η_μν. -/
def minkowskiComponent (μ ν : Fin 4) : ℝ :=
  if μ = 0 ∧ ν = 0 then -1
  else if μ = ν then 1
  else 0

/-- The trace-reversed perturbation: h̄_μν = h_μν - (1/2)η_μν h.
This simplifies the linearized Einstein equations. -/
def MetricPerturbation.traceReversed (hp : MetricPerturbation) :
    Fin 4 → Fin 4 → ℝ → ℝ → ℝ → ℝ → ℝ :=
  fun μ ν t x y z =>
    let h_tr := hp.trace t x y z
    hp.h μ ν t x y z - (1/2) * minkowskiComponent μ ν * h_tr

/-! ## Gauge Transformations -/

/-- An infinitesimal gauge transformation generated by a vector field ξ^μ.
Under x^μ → x^μ + ξ^μ, the perturbation transforms as:
h_μν → h_μν - ∂_μ ξ_ν - ∂_ν ξ_μ -/
structure GaugeTransformation where
  /-- The gauge vector field ξ^μ -/
  ξ : Fin 4 → ℝ → ℝ → ℝ → ℝ → ℝ

/-- The Lorenz gauge condition (de Donder gauge): ∂^μ h̄_μν = 0.
This is the gravitational analog of the Lorenz gauge in electromagnetism. -/
structure LorenzGauge extends MetricPerturbation where
  /-- The Lorenz condition is satisfied -/
  lorenz_condition : True  -- ∂^μ h̄_μν = 0 for all ν

/-! ## Gravitational Waves -/

/-- The transverse-traceless (TT) gauge for gravitational waves.
In this gauge:
- h_0μ = 0 (temporal components vanish)
- h^i_i = 0 (traceless in spatial part)
- ∂^i h_ij = 0 (transverse: spatial divergence vanishes)

The TT gauge is the "physical" gauge where h_μν represents actual degrees of freedom. -/
structure TTGauge extends MetricPerturbation where
  /-- Temporal components vanish: h_0μ = 0 -/
  temporal_zero : ∀ μ t x y z, h 0 μ t x y z = 0
  /-- Spatial trace vanishes: h_11 + h_22 + h_33 = 0 -/
  spatial_traceless : ∀ t x y z, h 1 1 t x y z + h 2 2 t x y z + h 3 3 t x y z = 0

/-- In TT gauge, h_00 also vanishes by symmetry. -/
lemma TTGauge.h00_zero (tt : TTGauge) (t x y z : ℝ) : tt.h 0 0 t x y z = 0 :=
  tt.temporal_zero 0 t x y z

/-- A gravitational wave propagating in the z-direction.
In TT gauge, the only non-zero components are h_+ = h_xx = -h_yy and h_× = h_xy = h_yx. -/
structure GravitationalWave where
  /-- The plus (+) polarization amplitude -/
  h_plus : ℝ → ℝ  -- h_+(t - z)
  /-- The cross (×) polarization amplitude -/
  h_cross : ℝ → ℝ  -- h_×(t - z)
  /-- Wave frequency (for monochromatic waves) -/
  frequency : ℝ
  /-- Wave vector magnitude k = ω/c = ω (in c=1 units) -/
  wavenumber : ℝ
  /-- Dispersion relation: ω = k (waves travel at speed of light) -/
  dispersion : wavenumber = frequency

/-- The two polarizations of gravitational waves. -/
inductive GWPolarization
  | plus   -- h_+ mode: stretches x, compresses y (and vice versa)
  | cross  -- h_× mode: stretches along 45°, compresses along 135°

/-- A gravitational wave satisfies the dispersion relation ω = k. -/
lemma gw_dispersion (gw : GravitationalWave) : gw.wavenumber = gw.frequency :=
  gw.dispersion

/-! ## Monochromatic Plane Waves -/

/-- A monochromatic gravitational plane wave with frequency ω propagating in z-direction.
h_+ = A_+ cos(ω(t - z) + φ_+)
h_× = A_× cos(ω(t - z) + φ_×) -/
structure MonochromaticGW extends GravitationalWave where
  /-- Amplitude of plus polarization -/
  A_plus : ℝ
  /-- Amplitude of cross polarization -/
  A_cross : ℝ
  /-- Phase of plus polarization -/
  φ_plus : ℝ
  /-- Phase of cross polarization -/
  φ_cross : ℝ
  /-- The wave functions have the monochromatic form -/
  h_plus_form : ∀ u, h_plus u = A_plus * Real.cos (frequency * u + φ_plus)
  h_cross_form : ∀ u, h_cross u = A_cross * Real.cos (frequency * u + φ_cross)

/-- A circularly polarized gravitational wave has equal amplitudes and 90° phase difference. -/
def isCircularlyPolarized (gw : MonochromaticGW) : Prop :=
  gw.A_plus = gw.A_cross ∧ |gw.φ_cross - gw.φ_plus| = Real.pi / 2

/-- A linearly polarized wave has one zero amplitude. -/
def isLinearlyPolarizedPlus (gw : MonochromaticGW) : Prop :=
  gw.A_cross = 0

/-- A linearly polarized wave has one zero amplitude. -/
def isLinearlyPolarizedCross (gw : MonochromaticGW) : Prop :=
  gw.A_plus = 0

/-! ## Quadrupole Formula -/

/-- The quadrupole moment tensor of a mass distribution:
Q_ij = ∫ ρ(x) (3 x_i x_j - |x|² δ_ij) d³x

This is the leading contribution to gravitational wave emission. -/
structure QuadrupoleMoment where
  /-- The quadrupole tensor Q_ij as a function of time -/
  Q : Fin 3 → Fin 3 → ℝ → ℝ
  /-- Symmetry -/
  symm : ∀ i j t, Q i j t = Q j i t
  /-- Traceless -/
  traceless : ∀ t, Q 0 0 t + Q 1 1 t + Q 2 2 t = 0

/-- The quadrupole moment is symmetric. -/
lemma QuadrupoleMoment.symmetric (Q : QuadrupoleMoment) (i j : Fin 3) (t : ℝ) :
    Q.Q i j t = Q.Q j i t := Q.symm i j t

/-! ## Binary Systems -/

/-- A circular binary system emitting gravitational waves. -/
structure BinaryGWSource where
  /-- Mass of first object -/
  m₁ : ℝ
  /-- Mass of second object -/
  m₂ : ℝ
  /-- Orbital separation -/
  a : ℝ
  /-- Distance to source -/
  r : ℝ
  /-- Both masses positive -/
  m₁_pos : m₁ > 0
  m₂_pos : m₂ > 0
  /-- Separation positive -/
  a_pos : a > 0
  /-- Distance positive -/
  r_pos : r > 0

/-- The total mass of a binary system. -/
def BinaryGWSource.totalMass (b : BinaryGWSource) : ℝ := b.m₁ + b.m₂

/-- The total mass is positive. -/
lemma BinaryGWSource.totalMass_pos (b : BinaryGWSource) : b.totalMass > 0 := by
  unfold BinaryGWSource.totalMass
  linarith [b.m₁_pos, b.m₂_pos]

/-- The reduced mass of a binary system: μ = m₁m₂/(m₁+m₂). -/
def BinaryGWSource.reducedMass (b : BinaryGWSource) : ℝ :=
  b.m₁ * b.m₂ / (b.m₁ + b.m₂)

/-- The reduced mass is positive. -/
lemma BinaryGWSource.reducedMass_pos (b : BinaryGWSource) : b.reducedMass > 0 := by
  unfold BinaryGWSource.reducedMass
  apply div_pos
  · exact mul_pos b.m₁_pos b.m₂_pos
  · exact b.totalMass_pos

/-- The symmetric mass ratio: η = μ/M = m₁m₂/(m₁+m₂)². -/
def BinaryGWSource.symmetricMassRatio (b : BinaryGWSource) : ℝ :=
  b.reducedMass / b.totalMass

/-- The symmetric mass ratio is positive. -/
lemma BinaryGWSource.eta_pos (b : BinaryGWSource) : b.symmetricMassRatio > 0 := by
  unfold BinaryGWSource.symmetricMassRatio
  exact div_pos b.reducedMass_pos b.totalMass_pos

/-- The symmetric mass ratio is at most 1/4 (equal mass case). -/
lemma BinaryGWSource.eta_le_quarter (b : BinaryGWSource) : b.symmetricMassRatio ≤ 1/4 := by
  unfold BinaryGWSource.symmetricMassRatio BinaryGWSource.reducedMass BinaryGWSource.totalMass
  have h : (b.m₁ - b.m₂)^2 ≥ 0 := sq_nonneg _
  have h2 : b.m₁^2 - 2 * b.m₁ * b.m₂ + b.m₂^2 ≥ 0 := by nlinarith
  have h3 : 4 * b.m₁ * b.m₂ ≤ (b.m₁ + b.m₂)^2 := by nlinarith
  have h4 : b.m₁ + b.m₂ > 0 := by linarith [b.m₁_pos, b.m₂_pos]
  have h5 : (b.m₁ + b.m₂)^2 > 0 := sq_pos_of_pos h4
  have hne : b.m₁ + b.m₂ ≠ 0 := ne_of_gt h4
  have h6 : b.m₁ * b.m₂ ≤ (b.m₁ + b.m₂)^2 / 4 := by linarith
  calc b.m₁ * b.m₂ / (b.m₁ + b.m₂) / (b.m₁ + b.m₂)
      = b.m₁ * b.m₂ / (b.m₁ + b.m₂)^2 := by field_simp [hne]
    _ ≤ (b.m₁ + b.m₂)^2 / 4 / (b.m₁ + b.m₂)^2 := by
        apply div_le_div_of_nonneg_right h6 (le_of_lt h5)
    _ = 1/4 := by field_simp [hne]

/-- The chirp mass M_c = (m_1 m_2)^(3/5) / (m_1 + m_2)^(1/5).
This combination determines the GW signal amplitude and frequency evolution. -/
def BinaryGWSource.chirpMass (b : BinaryGWSource) : ℝ :=
  Real.rpow (b.m₁ * b.m₂) (3/5) / Real.rpow (b.m₁ + b.m₂) (1/5)

/-- The orbital angular frequency from Kepler's law: ω² = GM/a³. -/
def BinaryGWSource.orbitalFrequency (b : BinaryGWSource) : ℝ :=
  Real.sqrt (b.totalMass / b.a^3)

/-- The orbital frequency is positive. -/
lemma BinaryGWSource.orbitalFrequency_pos (b : BinaryGWSource) :
    b.orbitalFrequency > 0 := by
  unfold BinaryGWSource.orbitalFrequency
  apply Real.sqrt_pos_of_pos
  apply div_pos b.totalMass_pos
  exact pow_pos b.a_pos 3

/-- The GW frequency is twice the orbital frequency (for circular orbits). -/
def BinaryGWSource.gwFrequency (b : BinaryGWSource) : ℝ :=
  2 * b.orbitalFrequency

/-- The GW frequency is positive. -/
lemma BinaryGWSource.gwFrequency_pos (b : BinaryGWSource) :
    b.gwFrequency > 0 := by
  unfold BinaryGWSource.gwFrequency
  linarith [b.orbitalFrequency_pos]

/-! ## Energy and Power -/

/-- The orbital energy of a binary (Newtonian approximation). -/
def BinaryGWSource.orbitalEnergy (b : BinaryGWSource) : ℝ :=
  -b.m₁ * b.m₂ / (2 * b.a)

/-- The orbital energy is negative (bound system). -/
lemma BinaryGWSource.orbitalEnergy_neg (b : BinaryGWSource) :
    b.orbitalEnergy < 0 := by
  unfold BinaryGWSource.orbitalEnergy
  have h : b.m₁ * b.m₂ / (2 * b.a) > 0 := by
    apply div_pos
    · exact mul_pos b.m₁_pos b.m₂_pos
    · linarith [b.a_pos]
  simp only [neg_mul, neg_div]
  linarith

/-- The GW luminosity formula (leading order):
L = (32/5) η² (M ω)^(10/3) in geometric units. -/
def BinaryGWSource.gwLuminosityFactor (b : BinaryGWSource) : ℝ :=
  (32/5) * b.symmetricMassRatio^2

/-- The luminosity factor is positive. -/
lemma BinaryGWSource.gwLuminosityFactor_pos (b : BinaryGWSource) :
    b.gwLuminosityFactor > 0 := by
  unfold BinaryGWSource.gwLuminosityFactor
  apply mul_pos
  · norm_num
  · exact sq_pos_of_pos b.eta_pos

/-! ## Binary Inspiral and Coalescence

The inspiral of a binary system due to gravitational wave emission is one of the
most important applications of GR. The coalescence time formula, derived from
the orbital decay rate, determines how long a binary takes to merge.

This is crucial for:
- Understanding binary pulsar evolution
- Gravitational wave detection and template matching
- Population synthesis of compact binaries

Reference: MTW Chapter 36, Peters & Mathews (1963)
-/

/-- The coalescence time for a circular binary system starting at separation a.
In geometric units (G = c = 1):
  t_c = (5/256) × a⁴/(μM²)

This is the time for the binary to inspiral from separation a to coalescence (a → 0).
For a binary starting at a₀, multiply the inspiral rate da/dt from orbitalDecayRate
and integrate to get this result. -/
def BinaryGWSource.coalescenceTime (b : BinaryGWSource) : ℝ :=
  (5/256) * b.a^4 / (b.reducedMass * b.totalMass^2)

/-- Alternative form: coalescence time in terms of individual masses.
t_c = (5/256) × a⁴ × (m₁ + m₂) / (m₁ × m₂ × (m₁ + m₂)²)
    = (5/256) × a⁴ / (m₁ × m₂ × (m₁ + m₂)) -/
def coalescenceTimeExplicit (m₁ m₂ a : ℝ) : ℝ :=
  (5/256) * a^4 / (m₁ * m₂ * (m₁ + m₂))

/-- The two forms of coalescence time are equal. -/
lemma BinaryGWSource.coalescenceTime_eq_explicit (b : BinaryGWSource) :
    b.coalescenceTime = coalescenceTimeExplicit b.m₁ b.m₂ b.a := by
  unfold BinaryGWSource.coalescenceTime coalescenceTimeExplicit
    BinaryGWSource.reducedMass BinaryGWSource.totalMass
  have hne : b.m₁ + b.m₂ ≠ 0 := ne_of_gt b.totalMass_pos
  field_simp [hne]

/-- The coalescence time is positive for a valid binary. -/
lemma BinaryGWSource.coalescenceTime_pos (b : BinaryGWSource) :
    b.coalescenceTime > 0 := by
  unfold BinaryGWSource.coalescenceTime
  apply div_pos
  · apply mul_pos (by norm_num : (5/256 : ℝ) > 0)
    exact pow_pos b.a_pos 4
  · apply mul_pos b.reducedMass_pos
    exact sq_pos_of_pos b.totalMass_pos

/-- Coalescence time scales as a⁴. Doubling the separation increases time by 16×. -/
lemma coalescenceTime_scaling (m₁ m₂ a c : ℝ) :
    coalescenceTimeExplicit m₁ m₂ (c * a) = c^4 * coalescenceTimeExplicit m₁ m₂ a := by
  unfold coalescenceTimeExplicit
  ring

/-- For equal-mass binaries (m₁ = m₂ = m), the coalescence time simplifies.
t_c = (5/256) × a⁴ / (m × m × 2m) = (5/512) × a⁴ / m³ -/
def equalMassCoalescenceTime (m a : ℝ) : ℝ :=
  (5/512) * a^4 / m^3

/-- Coalescence time for equal masses equals the general formula. -/
lemma equalMass_coalescenceTime_eq (m a : ℝ) (hm : m > 0) :
    coalescenceTimeExplicit m m a = equalMassCoalescenceTime m a := by
  unfold coalescenceTimeExplicit equalMassCoalescenceTime
  have hne : m ≠ 0 := ne_of_gt hm
  field_simp [hne]
  ring

/-- The frequency at time t before coalescence (simplified chirp evolution).
f(t) ∝ t^(-3/8) for the dominant harmonic. -/
def frequencyEvolutionExponent : ℝ := -3/8

/-- The GW amplitude increases as separation decreases: h ∝ 1/a ∝ f^(2/3).
This is why the "chirp" signal gets louder as it approaches merger. -/
lemma amplitude_frequency_relation : (2 : ℝ) / 3 = 2/3 := by norm_num

/-! ## Strain Amplitude -/

/-- The characteristic strain amplitude for a binary:
h ~ (M_c)^(5/3) × f^(2/3) / r
where M_c is the chirp mass, f is the GW frequency, and r is the distance.
This is the amplitude that gravitational wave detectors measure. -/
def strainAmplitudeFactor (chirpMass frequency distance : ℝ) : ℝ :=
  Real.rpow chirpMass (5/3) * Real.rpow frequency (2/3) / distance

/-- The strain amplitude is positive for positive parameters. -/
lemma strainAmplitude_pos (mc f r : ℝ) (hmc : mc > 0) (hf : f > 0) (hr : r > 0) :
    strainAmplitudeFactor mc f r > 0 := by
  unfold strainAmplitudeFactor
  apply div_pos
  · apply mul_pos
    · exact Real.rpow_pos_of_pos hmc (5/3)
    · exact Real.rpow_pos_of_pos hf (2/3)
  · exact hr

end PseudoRiemannianMetric
end
