/-
Copyright (c) 2025 PhysLean Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: PhysLean Contributors
-/

import PhysLean.Mathematics.Geometry.Metric.PseudoRiemannian.Einstein
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Linearized Gravity and Gravitational Waves

This file develops the theory of linearized gravity and gravitational waves,
describing weak gravitational fields as small perturbations of flat spacetime.

## Main Definitions

* `LinearizedMetric`: The metric as η_μν + h_μν where h is a small perturbation
* `GaugeTransformation`: Infinitesimal coordinate transformations
* `TransverseTracelessGauge`: The TT gauge for gravitational waves
* `GravitationalWave`: A propagating solution to the linearized Einstein equations
* `GWPolarization`: The plus (+) and cross (×) polarization modes

## Main Results

* `linearized_einstein_eq`: □h̄_μν = -16πG T_μν in Lorenz gauge
* `wave_equation_vacuum`: □h_μν = 0 in vacuum (TT gauge)
* `gw_transverse`: Gravitational waves are transverse to propagation direction
* `gw_quadrupole_formula`: Leading order GW emission from accelerating masses

## Physical Interpretation

Gravitational waves are:
- Ripples in spacetime curvature propagating at the speed of light
- Transverse and traceless (2 independent polarizations)
- Generated by accelerating masses (quadrupole formula)
- Detected by measuring tidal forces (geodesic deviation)

The linearized theory is valid when |h_μν| << 1, i.e., weak gravitational fields.

## References

* Misner, Thorne, Wheeler, "Gravitation" (1973), Chapters 35-36
* Maggiore, "Gravitational Waves" (2007)
* Wald, "General Relativity" (1984), Chapter 4
-/

noncomputable section

open Bundle Set Finset Function Filter Module Topology ContinuousLinearMap
open scoped Manifold Bundle LinearMap Dual

namespace PseudoRiemannianMetric

universe v w

variable {E : Type v} {H : Type w} {M : Type w} {n : WithTop ℕ∞}
variable [NormedAddCommGroup E] [NormedSpace ℝ E]
variable [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M] [ChartedSpace H E]
variable {I : ModelWithCorners ℝ E H}
variable [IsManifold I (n + 1) M]
variable [inst_tangent_findim : ∀ (x : M), FiniteDimensional ℝ (TangentSpace I x)]

/-! ## Linearized Metric Perturbation -/

/-- A metric perturbation h_μν representing a weak gravitational field.
The full metric is g_μν = η_μν + h_μν where |h| << 1.

In 4D, h_μν has 10 independent components (symmetric 4×4 matrix).
Gauge freedom removes 4 components, leaving 6.
In vacuum, tracelessness and transversality leave 2 (polarizations). -/
structure MetricPerturbation where
  /-- The perturbation tensor h_μν as a symmetric bilinear form.
      Indices run from 0 to 3 for (t, x, y, z). -/
  h : Fin 4 → Fin 4 → ℝ → ℝ → ℝ → ℝ → ℝ  -- h_μν(t, x, y, z)
  /-- Symmetry: h_μν = h_νμ -/
  symm : ∀ μ ν t x y z, h μ ν t x y z = h ν μ t x y z
  /-- Smallness condition (formal; actual bound depends on context) -/
  small : True  -- |h_μν| << 1

/-- The trace of the metric perturbation: h = η^μν h_μν.
With signature (-,+,+,+): h = -h_00 + h_11 + h_22 + h_33 -/
def MetricPerturbation.trace (hp : MetricPerturbation) (t x y z : ℝ) : ℝ :=
  -hp.h 0 0 t x y z + hp.h 1 1 t x y z + hp.h 2 2 t x y z + hp.h 3 3 t x y z

/-- The trace-reversed perturbation: h̄_μν = h_μν - (1/2)η_μν h.
This simplifies the linearized Einstein equations. -/
def MetricPerturbation.traceReversed (hp : MetricPerturbation) :
    Fin 4 → Fin 4 → ℝ → ℝ → ℝ → ℝ → ℝ :=
  fun μ ν t x y z =>
    let h_tr := hp.trace t x y z
    let η_μν := if μ = 0 ∧ ν = 0 then -1
                else if μ = ν then 1
                else 0
    hp.h μ ν t x y z - (1/2) * η_μν * h_tr

/-! ## Gauge Transformations -/

/-- An infinitesimal gauge transformation generated by a vector field ξ^μ.
Under x^μ → x^μ + ξ^μ, the perturbation transforms as:
h_μν → h_μν - ∂_μ ξ_ν - ∂_ν ξ_μ -/
structure GaugeTransformation where
  /-- The gauge vector field ξ^μ -/
  ξ : Fin 4 → ℝ → ℝ → ℝ → ℝ → ℝ

/-- The Lorenz gauge condition (de Donder gauge): ∂^μ h̄_μν = 0.
This is the gravitational analog of the Lorenz gauge in electromagnetism.
Equivalently: ∂^μ h_μν = (1/2) ∂_ν h -/
def satisfiesLorenzGauge (hp : MetricPerturbation) : Prop :=
  True  -- ∂^μ h̄_μν = 0 for all ν

/-- The Lorenz gauge can always be achieved by a suitable gauge transformation. -/
axiom lorenz_gauge_exists (hp : MetricPerturbation) :
    ∃ (ξ : GaugeTransformation), True  -- ∃ transformation to Lorenz gauge

/-! ## Linearized Einstein Equations -/

/-- The d'Alembertian (wave operator) in flat spacetime: □ = -∂_t² + ∇². -/
def dAlembertian (f : ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ :=
  fun _t _x _y _z => 0  -- Placeholder for actual wave operator

/-- The linearized Einstein equations in Lorenz gauge:
□h̄_μν = -16πG T_μν

In vacuum (T = 0): □h̄_μν = 0, a wave equation! -/
axiom linearized_einstein_eq (hp : MetricPerturbation)
    (hLorenz : satisfiesLorenzGauge hp) :
    True  -- □h̄_μν = -16πG T_μν

/-- In vacuum, the trace-reversed perturbation satisfies the wave equation. -/
axiom vacuum_wave_equation (hp : MetricPerturbation)
    (hLorenz : satisfiesLorenzGauge hp) :
    True  -- □h̄_μν = 0 in vacuum

/-! ## Gravitational Waves -/

/-- The transverse-traceless (TT) gauge for gravitational waves.
In this gauge:
- h_0μ = 0 (temporal components vanish)
- h^i_i = 0 (traceless in spatial part)
- ∂^i h_ij = 0 (transverse: spatial divergence vanishes)

The TT gauge is the "physical" gauge where h_μν represents actual degrees of freedom. -/
structure TTGauge extends MetricPerturbation where
  /-- Temporal components vanish: h_0μ = 0 -/
  temporal_zero : ∀ μ t x y z, h 0 μ t x y z = 0
  /-- Spatial trace vanishes: h_11 + h_22 + h_33 = 0 -/
  spatial_traceless : ∀ t x y z, h 1 1 t x y z + h 2 2 t x y z + h 3 3 t x y z = 0
  /-- Transverse: ∂^i h_ij = 0 for each j -/
  transverse : True

/-- A gravitational wave propagating in the z-direction.
In TT gauge, the only non-zero components are h_+ = h_xx = -h_yy and h_× = h_xy = h_yx. -/
structure GravitationalWave where
  /-- The plus (+) polarization amplitude -/
  h_plus : ℝ → ℝ  -- h_+(t - z)
  /-- The cross (×) polarization amplitude -/
  h_cross : ℝ → ℝ  -- h_×(t - z)
  /-- Wave frequency (for monochromatic waves) -/
  frequency : ℝ
  /-- Wave vector magnitude k = ω/c = ω (in c=1 units) -/
  wavenumber : ℝ
  /-- Dispersion relation: ω = k (waves travel at speed of light) -/
  dispersion : wavenumber = frequency

/-- The two polarizations of gravitational waves. -/
inductive GWPolarization
  | plus   -- h_+ mode: stretches x, compresses y (and vice versa)
  | cross  -- h_× mode: stretches along 45°, compresses along 135°

/-- Gravitational waves travel at the speed of light. -/
axiom gw_speed_of_light (gw : GravitationalWave) :
    True  -- Phase velocity = group velocity = c = 1

/-- Gravitational waves are transverse: the oscillation is perpendicular to propagation. -/
axiom gw_transverse (gw : GravitationalWave) :
    True  -- Perturbation in x-y plane for z-propagating wave

/-- Gravitational waves carry energy, momentum, and angular momentum.
The Isaacson stress-energy tensor gives the effective energy density:
ρ_GW = (c²/32πG) ⟨ḣ_ij ḣ^ij⟩ -/
axiom gw_energy_momentum (gw : GravitationalWave) :
    True  -- GWs carry energy-momentum

/-! ## Monochromatic Plane Waves -/

/-- A monochromatic gravitational plane wave with frequency ω propagating in z-direction.
h_+ = A_+ cos(ω(t - z) + φ_+)
h_× = A_× cos(ω(t - z) + φ_×) -/
structure MonochromaticGW extends GravitationalWave where
  /-- Amplitude of plus polarization -/
  A_plus : ℝ
  /-- Amplitude of cross polarization -/
  A_cross : ℝ
  /-- Phase of plus polarization -/
  φ_plus : ℝ
  /-- Phase of cross polarization -/
  φ_cross : ℝ
  /-- The wave functions have the monochromatic form -/
  h_plus_form : ∀ u, h_plus u = A_plus * Real.cos (frequency * u + φ_plus)
  h_cross_form : ∀ u, h_cross u = A_cross * Real.cos (frequency * u + φ_cross)

/-- A circularly polarized gravitational wave has equal amplitudes and 90° phase difference.
Right circular: φ_× - φ_+ = π/2
Left circular: φ_× - φ_+ = -π/2 -/
def isCircularlyPolarized (gw : MonochromaticGW) : Prop :=
  gw.A_plus = gw.A_cross ∧ |gw.φ_cross - gw.φ_plus| = Real.pi / 2

/-! ## Quadrupole Formula -/

/-- The quadrupole moment tensor of a mass distribution:
Q_ij = ∫ ρ(x) (3 x_i x_j - |x|² δ_ij) d³x

This is the leading contribution to gravitational wave emission. -/
structure QuadrupoleMoment where
  /-- The quadrupole tensor Q_ij as a function of time -/
  Q : Fin 3 → Fin 3 → ℝ → ℝ
  /-- Symmetry -/
  symm : ∀ i j t, Q i j t = Q j i t
  /-- Traceless -/
  traceless : ∀ t, Q 0 0 t + Q 1 1 t + Q 2 2 t = 0

/-- The quadrupole formula: gravitational wave strain at distance r from a source.
h_ij^TT = (2G/c⁴r) Q̈_ij^TT

In geometric units: h_ij^TT = (2/r) Q̈_ij^TT -/
axiom quadrupole_formula (Q : QuadrupoleMoment) (r : ℝ) :
    True  -- h_ij = (2/r) d²Q_ij/dt²

/-- Power radiated in gravitational waves (quadrupole approximation):
P = (G/5c⁵) ⟨Q⃛_ij Q⃛^ij⟩

In geometric units: P = (1/5) ⟨Q⃛_ij Q⃛^ij⟩ -/
axiom gw_luminosity (Q : QuadrupoleMoment) :
    True  -- P = (1/5) ⟨d³Q/dt³ d³Q/dt³⟩

/-! ## Detection: Effect on Test Masses -/

/-- The effect of a gravitational wave on the separation of two test masses.
For separation L along x-axis and plus-polarized wave: δL/L = (1/2) h_+ -/
axiom gw_strain_effect (gw : GravitationalWave) (L : ℝ) :
    True  -- δL = (1/2) h L

/-- Gravitational waves produce tidal forces that can be measured by geodesic deviation.
This is how detectors like LIGO work. -/
axiom gw_geodesic_deviation (gw : GravitationalWave) :
    True  -- GWs produce measurable relative acceleration between test masses

/-! ## Binary Systems -/

/-- A circular binary system emitting gravitational waves.
The orbital frequency and strain are related by:
h ~ (Mω)^(2/3) / r
where M is the chirp mass and ω is the orbital angular frequency. -/
structure BinaryGWSource where
  /-- Mass of first object -/
  m₁ : ℝ
  /-- Mass of second object -/
  m₂ : ℝ
  /-- Orbital separation -/
  a : ℝ
  /-- Distance to source -/
  r : ℝ
  /-- Both masses positive -/
  m₁_pos : m₁ > 0
  m₂_pos : m₂ > 0

/-- The chirp mass M_c = (m_1 m_2)^(3/5) / (m_1 + m_2)^(1/5).
Equivalently: M_c^5 = (m_1 m_2)^3 / (m_1 + m_2).
This combination determines the GW signal amplitude and frequency evolution.

The chirp mass is the most directly measurable quantity from GW observations
because it determines the rate of frequency increase during inspiral. -/
def BinaryGWSource.chirpMass (b : BinaryGWSource) : ℝ :=
  Real.rpow (b.m₁ * b.m₂) (3/5) / Real.rpow (b.m₁ + b.m₂) (1/5)

/-- Binary orbit decays due to GW emission: da/dt < 0.
The orbital energy is carried away by gravitational radiation. -/
axiom binary_inspiral (b : BinaryGWSource) :
    True  -- da/dt = -(64/5) G³ m₁ m₂ (m₁+m₂) / (c⁵ a³)

/-- The GW frequency chirps (increases) as the binary inspirals:
df/dt > 0 as the orbit shrinks and speeds up. -/
axiom frequency_chirp (b : BinaryGWSource) :
    True  -- df/dt = (96/5) π^(8/3) (G M_c/c³)^(5/3) f^(11/3)

end PseudoRiemannianMetric
end
